"""Add tournament and squad relationships to bowler

Revision ID: 9ebf3657909f
Revises: f0617e616df4
Create Date: 2025-09-22 12:09:46.007921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebf3657909f'
down_revision: Union[str, Sequence[str], None] = 'f0617e616df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First add columns as nullable
    op.add_column('bowler', sa.Column('tournament_id', sa.Integer(), nullable=True))
    op.add_column('bowler', sa.Column('squad_id', sa.Integer(), nullable=True))
    op.add_column('bowler', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Create a default tournament and user for existing bowlers
    connection = op.get_bind()
    
    # Check if there are any existing bowlers
    result = connection.execute(sa.text("SELECT COUNT(*) FROM bowler")).scalar()
    
    if result > 0:
        # Create a default user if none exists
        user_result = connection.execute(sa.text("SELECT id FROM users LIMIT 1"))
        user_row = user_result.fetchone()
        if user_row is None:
            # Create a default admin user
            connection.execute(sa.text("""
                INSERT INTO users (username, email, first_name, last_name, password, is_admin) 
                VALUES ('admin', 'admin@example.com', 'Admin', 'User', 'temp_password', true)
            """))
            default_user_id = connection.execute(sa.text("SELECT id FROM users WHERE username = 'admin'")).scalar()
        else:
            default_user_id = user_row[0]
        
        # Create a default tournament if none exists
        tournament_result = connection.execute(sa.text("SELECT id FROM tournament LIMIT 1"))
        tournament_row = tournament_result.fetchone()
        if tournament_row is None:
            # Create a default tournament
            connection.execute(sa.text("""
                INSERT INTO tournament (user_id, name, location, start_date, end_date) 
                VALUES (:user_id, 'Default Tournament', 'Default Location', '2024-01-01', '2024-01-01')
            """), {"user_id": default_user_id})
            default_tournament_id = connection.execute(sa.text("SELECT id FROM tournament WHERE name = 'Default Tournament'")).scalar()
        else:
            default_tournament_id = tournament_row[0]
        
        # Update existing bowlers with default values
        connection.execute(sa.text("""
            UPDATE bowler 
            SET tournament_id = :tournament_id, user_id = :user_id 
            WHERE tournament_id IS NULL OR user_id IS NULL
        """), {"tournament_id": default_tournament_id, "user_id": default_user_id})
    
    # Now make tournament_id and user_id non-nullable
    op.alter_column('bowler', 'tournament_id', nullable=False)
    op.alter_column('bowler', 'user_id', nullable=False)
    op.create_index(op.f('ix_bowler_squad_id'), 'bowler', ['squad_id'], unique=False)
    op.create_index(op.f('ix_bowler_tournament_id'), 'bowler', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_bowler_user_id'), 'bowler', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bowler', 'squad', ['squad_id'], ['id'])
    op.create_foreign_key(None, 'bowler', 'tournament', ['tournament_id'], ['id'])
    op.create_foreign_key(None, 'bowler', 'users', ['user_id'], ['id'])
    op.add_column('bracket_settings', sa.Column('handicap_percentage', sa.Float(), nullable=True))
    op.add_column('bracket_settings', sa.Column('handicap_base', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bracket_settings', 'handicap_base')
    op.drop_column('bracket_settings', 'handicap_percentage')
    op.drop_constraint(None, 'bowler', type_='foreignkey')
    op.drop_constraint(None, 'bowler', type_='foreignkey')
    op.drop_constraint(None, 'bowler', type_='foreignkey')
    op.drop_index(op.f('ix_bowler_user_id'), table_name='bowler')
    op.drop_index(op.f('ix_bowler_tournament_id'), table_name='bowler')
    op.drop_index(op.f('ix_bowler_squad_id'), table_name='bowler')
    op.drop_column('bowler', 'user_id')
    op.drop_column('bowler', 'squad_id')
    op.drop_column('bowler', 'tournament_id')
    # ### end Alembic commands ###
