import type { TournamentDetails } from './setupTypes';

export const DRAFT_VERSION = 1;

export function getDraftStorageKey(): string {
  if (typeof window === 'undefined') {
    return 'tc_organizer_setup_draft';
  }

  const userId = (localStorage.getItem('user_id') || '').trim();
  return userId ? `tc_organizer_setup_draft_user_${userId}` : 'tc_organizer_setup_draft';
}

export const defaultTournamentDetails: TournamentDetails = {
  name: '',
  subtitle: '',
  organizer: '',
  tournamentType: '',
  startDateIso: '',
  endDateIso: '',
  venueId: null,
  bowlingCenter: '',
  venueAddressLine1: '',
  venueAddressLine2: '',
  city: '',
  state: '',
  venueZip: '',
  venueCountry: 'US',
  venueLatitude: null,
  venueLongitude: null,
  venueExternalProvider: '',
  venueExternalPlaceId: '',
  timezone: 'America/Denver',
  visibility: 'private',
  tournamentStatus: 'draft',
  supportEmail: '',
  supportPhone: '',
  contactName: '',
  contactRole: '',
  preferredContactMethod: 'email',
  contactNote: '',
  registrationOpenIso: '',
  registrationCloseIso: '',
  registrationOpenTime: '00:00',
  registrationCloseTime: '23:59',
  logoFileName: '',
};

export const TIMEZONES = [
  { value: 'America/New_York', label: 'Eastern Time — America/New_York' },
  { value: 'America/Chicago', label: 'Central Time — America/Chicago' },
  { value: 'America/Denver', label: 'Mountain Time — America/Denver' },
  { value: 'America/Boise', label: 'Mountain Time — America/Boise' },
  { value: 'America/Los_Angeles', label: 'Pacific Time — America/Los_Angeles' },
  { value: 'America/Phoenix', label: 'Arizona Time — America/Phoenix' },
  { value: 'America/Anchorage', label: 'Alaska Time — America/Anchorage' },
  { value: 'Pacific/Honolulu', label: 'Hawaii Time — Pacific/Honolulu' },
];

export const US_STATES: Array<{ code: string; name: string }> = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
];
