import { Player } from '../../lib/types'
import { calculateDisplayTotal, calculateTotalScratch } from './scoreUtils'

type BuildScoresPdfHtmlArgs = {
  players: Player[]
  tournamentName: string
  squadLabel: string
  location: string
  generatedAt: string
  logoUrl: string
  scoresLocked: boolean
}

const escapeHtml = (value: string | number): string =>
  String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')

const displayScore = (value: number | undefined): string => value === undefined ? '&mdash;' : String(value)

export function buildScoresPdfHtml({
  players,
  tournamentName,
  squadLabel,
  location,
  generatedAt,
  logoUrl,
  scoresLocked,
}: BuildScoresPdfHtmlArgs): string {
  const completedPlayers = players.filter(player => [
    player.scores?.game1_scratch,
    player.scores?.game2_scratch,
    player.scores?.game3_scratch,
  ].every(score => score !== undefined)).length
  const allGames = players.flatMap(player => [
    player.scores?.game1_scratch,
    player.scores?.game2_scratch,
    player.scores?.game3_scratch,
  ]).filter((score): score is number => score !== undefined)
  const highGame = allGames.length > 0 ? Math.max(...allGames) : 0
  const highSeries = players.reduce((highest, player) => Math.max(highest, calculateTotalScratch(player)), 0)
  const averageSeries = players.length > 0
    ? Math.round(players.reduce((sum, player) => sum + calculateTotalScratch(player), 0) / players.length)
    : 0

  const statItems: Array<[string, string | number]> = [
    ['Players', players.length],
    ['Complete', `${completedPlayers} / ${players.length}`],
    ['High Game', highGame || '&mdash;'],
    ['High Series', highSeries || '&mdash;'],
    ['Average Series', averageSeries || '&mdash;'],
    ['Status', scoresLocked ? 'Locked' : 'In Progress'],
  ]
  const statCards = statItems.map(([label, value]) => `<div class="stat-card">
      <span class="stat-label">${escapeHtml(label)}</span>
      <strong class="stat-value">${typeof value === 'string' && value === '&mdash;' ? value : escapeHtml(value)}</strong>
    </div>`).join('')

  const rows = players.map((player, index) => {
    const name = player.fullName || `${player.firstName || ''} ${player.lastName || ''}`.trim() || 'Unknown Player'
    return `<tr>
      <td class="rank">${index + 1}</td>
      <td class="player">${escapeHtml(name)}</td>
      <td class="lane">${escapeHtml(player.lane ?? '')}</td>
      <td class="number">${escapeHtml(player.handicap ?? 0)}</td>
      <td class="number">${displayScore(player.scores?.game1_scratch)}</td>
      <td class="number">${displayScore(player.scores?.game2_scratch)}</td>
      <td class="number">${displayScore(player.scores?.game3_scratch)}</td>
      <td class="number total">${escapeHtml(calculateTotalScratch(player))}</td>
      <td class="number total">${escapeHtml(calculateDisplayTotal(player))}</td>
    </tr>`
  }).join('')

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Score Distribution - ${escapeHtml(tournamentName)}</title>
  <link rel="stylesheet" href="/scores-print.css" />
</head>
<body>
  <main class="page">
    <header class="brand-header">
      <section class="brand-left">
        <img src="${escapeHtml(logoUrl)}" alt="" class="logo" />
        <div><h2>BracketWorks</h2><p>Bowling Brackets &amp; Side Pots</p></div>
      </section>
      <section class="report-title"><h1>Score Distribution</h1><p>Official tournament score sheet</p></section>
    </header>
    <section class="event-band">
      <div><h2>${escapeHtml(tournamentName)}</h2><p>${escapeHtml(squadLabel)}</p></div>
      <div class="event-right"><span>Generated ${escapeHtml(generatedAt)}</span><strong>${escapeHtml(location || 'Tournament scores')}</strong></div>
    </section>
    <section class="stats">${statCards}</section>
    <table>
      <thead><tr><th class="rank">#</th><th>Player Name</th><th class="lane">Lane</th><th class="number">Hcp</th><th class="number">Game 1</th><th class="number">Game 2</th><th class="number">Game 3</th><th class="number">Scratch</th><th class="number">Total</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <section class="verification">
      <div><strong>Commissioner Verification</strong><p>I verify that the scores above are accurate and approved as the official tournament results.</p></div>
      <div class="signature"><span></span><small>Commissioner / Tournament Director</small></div>
      <div class="date"><span></span><small>Date</small></div>
    </section>
    <footer><strong>BracketWorks &nbsp;|&nbsp; bracketworks.app</strong><span>Generated by BracketWorks. Scores are subject to commissioner verification.</span></footer>
  </main>
</body>
</html>`
}
