import { PayoutExportRow } from './payoutExportRows'

type BuildPayoutPdfHtmlArgs = {
  rows: PayoutExportRow[]
  tournamentName: string
  squadLabel: string
  generatedAt: string
  paidStampDate: string
  logoUrl: string
  programs: string
  totalBrackets: number
  totalEntries: number
  documentStatus?: string
}

type PayoutTotals = {
  bracketPayouts: number
  sidePotPayouts: number
  totalPayout: number
  paidCount: number
}

type PayoutPage = {
  rows: PayoutExportRow[]
  continued: boolean
  includeVerification: boolean
}

const FIRST_PAGE_ROW_LIMIT = 22
const CONTINUATION_PAGE_ROW_LIMIT = 28
const FINAL_PAGE_WITH_VERIFICATION_ROW_LIMIT = 12
const DEFAULT_DOCUMENT_STATUS = 'PENDING VERIFICATION'
const CHECKBOX_UNPAID = '&#9744;'
const CHECKBOX_PAID = '&#9745;'
const DISCLAIMER = 'Generated by BracketWorks. Payout amounts are based on tournament settings and are subject to commissioner verification. BracketWorks does not collect entry fees, hold funds, distribute winnings, or determine prize structures.'

const escapeHtml = (value: string): string =>
  String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')

const formatUsd = (value: number): string => {
  const rounded = Math.round(Number(value) || 0)
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(rounded)
}

const sum = (rows: PayoutExportRow[], selector: (row: PayoutExportRow) => number): number =>
  rows.reduce((total, row) => total + Math.round(Number(selector(row)) || 0), 0)

const buildPayoutTotals = (rows: PayoutExportRow[]): PayoutTotals => {
  const bracketPayouts = sum(rows, row => row.bracketTotal)
  const sidePotPayouts = sum(rows, row => row.sidePotTotal)
  const totalPayout = sum(rows, row => row.totalWon)
  const reconciledTotal = bracketPayouts + sidePotPayouts

  if (totalPayout !== reconciledTotal && process.env.NODE_ENV !== 'production') {
    console.warn('Payout export totals do not reconcile.', {
      bracketPayouts,
      sidePotPayouts,
      totalPayout,
      reconciledTotal,
    })
  }

  return {
    bracketPayouts,
    sidePotPayouts,
    totalPayout,
    paidCount: rows.filter(row => row.isPaid).length,
  }
}

const avoidSingleRowFinalPage = (pages: PayoutPage[]): PayoutPage[] => {
  const lastPage = pages[pages.length - 1]
  const previousPage = pages[pages.length - 2]
  if (!lastPage || !previousPage || lastPage.rows.length !== 1 || previousPage.rows.length <= 1) return pages

  const movedRows = previousPage.rows.slice(-1)
  previousPage.rows = previousPage.rows.slice(0, -1)
  lastPage.rows = [...movedRows, ...lastPage.rows]
  return pages
}

const paginateRows = (rows: PayoutExportRow[]): PayoutPage[] => {
  if (rows.length === 0) {
    return [{ rows: [], continued: false, includeVerification: true }]
  }

  const pages: PayoutPage[] = []
  let cursor = 0

  pages.push({ rows: rows.slice(cursor, cursor + FIRST_PAGE_ROW_LIMIT), continued: false, includeVerification: false })
  cursor += FIRST_PAGE_ROW_LIMIT

  while (cursor < rows.length) {
    pages.push({ rows: rows.slice(cursor, cursor + CONTINUATION_PAGE_ROW_LIMIT), continued: true, includeVerification: false })
    cursor += CONTINUATION_PAGE_ROW_LIMIT
  }

  avoidSingleRowFinalPage(pages)

  const finalPage = pages[pages.length - 1]
  if (finalPage && finalPage.rows.length <= FINAL_PAGE_WITH_VERIFICATION_ROW_LIMIT) {
    finalPage.includeVerification = true
  }

  return pages
}

const renderDocumentHeader = ({
  tournamentName,
  squadLabel,
  generatedAt,
  logoUrl,
  programs,
  documentStatus,
  continued,
}: Pick<BuildPayoutPdfHtmlArgs, 'tournamentName' | 'squadLabel' | 'generatedAt' | 'logoUrl' | 'programs'> & {
  documentStatus: string
  continued: boolean
}): string => {
  if (continued) {
    return `<header class="document-header continuation-header">
      <section class="brand-left">
        <img src="${escapeHtml(logoUrl)}" alt="BracketWorks" class="logo compact-logo" />
        <div>
          <h2 class="brand-name compact-brand-name">BracketWorks</h2>
          <p class="brand-tagline">Bowling Brackets &amp; Side Pots</p>
        </div>
      </section>
      <section class="report-title">
        <h1>Payout Distribution &mdash; Continued</h1>
        <p>${escapeHtml(tournamentName)}</p>
        <span class="document-status">${escapeHtml(documentStatus)}</span>
      </section>
    </header>`
  }

  return `<header class="document-header">
    <section class="brand-left">
      <img src="${escapeHtml(logoUrl)}" alt="BracketWorks" class="logo" />
      <div>
        <h2 class="brand-name">BracketWorks</h2>
        <p class="brand-tagline">Bowling Brackets &amp; Side Pots</p>
      </div>
    </section>
    <section class="report-title">
      <h1>Payout Distribution</h1>
      <p>Official Tournament Payout Sheet</p>
      <span class="document-status">${escapeHtml(documentStatus)}</span>
    </section>
  </header>
  <section class="tournament-info">
    <div>
      <h2>${escapeHtml(tournamentName)}</h2>
      <p>${escapeHtml(squadLabel)}</p>
    </div>
    <div class="generated-block">
      <span>Generated</span>
      <strong>${escapeHtml(generatedAt)}</strong>
    </div>
  </section>
  <section class="programs-block">
    <span>Programs</span>
    <strong>${escapeHtml(programs)}</strong>
  </section>`
}

const renderSummaryMetric = (value: string, label: string): string =>
  `<div class="summary-cell"><strong>${escapeHtml(value)}</strong><span>${escapeHtml(label)}</span></div>`

const renderSummary = ({
  totals,
  totalBrackets,
  totalEntries,
  winnerCount,
}: {
  totals: PayoutTotals
  totalBrackets: number
  totalEntries: number
  winnerCount: number
}): string =>
  `<section class="summary-section" aria-label="Payout summary">
    <div class="summary-strip">
      ${renderSummaryMetric(String(totalBrackets), 'Brackets')}
      ${renderSummaryMetric(String(totalEntries), 'Entries')}
      ${renderSummaryMetric(String(winnerCount), 'Winners')}
      ${renderSummaryMetric(formatUsd(totals.totalPayout), 'Prize Pool')}
      ${renderSummaryMetric(`${totals.paidCount} / ${winnerCount}`, 'Paid')}
    </div>
    <div class="payout-breakdown">
      <div><span>Bracket Payouts</span><strong>${formatUsd(totals.bracketPayouts)}</strong></div>
      <div><span>Side Pots</span><strong>${totals.sidePotPayouts > 0 ? formatUsd(totals.sidePotPayouts) : '&mdash;'}</strong></div>
      <div><span>Total Payout</span><strong>${formatUsd(totals.totalPayout)}</strong></div>
    </div>
  </section>`

const renderWinnerRows = (rows: PayoutExportRow[]): string =>
  rows
    .map(row => `<tr class="${row.isPaid ? 'is-paid-row' : ''}">
      <td class="rank">${row.rank}</td>
      <td class="player">${escapeHtml(row.playerName)}</td>
      <td class="amount">${row.bracketTotal > 0 ? formatUsd(row.bracketTotal) : '&mdash;'}</td>
      <td class="amount side-pot-amount ${row.sidePotTotal > 0 ? 'has-side-pot' : 'empty-cell'}">${row.sidePotTotal > 0 ? formatUsd(row.sidePotTotal) : '&mdash;'}</td>
      <td class="amount total-amount">${formatUsd(row.totalWon)}</td>
      <td class="paid-cell"><span class="paid-checkbox" aria-hidden="true">${row.isPaid ? CHECKBOX_PAID : CHECKBOX_UNPAID}</span><span class="paid-label">${row.isPaid ? 'Paid' : 'Unpaid'}</span></td>
      <td class="signature-cell"><span class="signature-line"></span></td>
    </tr>`)
    .join('')

const renderWinnerTable = (rows: PayoutExportRow[]): string =>
  `<table class="winner-table">
    <thead>
      <tr>
        <th class="rank">#</th>
        <th class="player">Player</th>
        <th class="amount">Brackets</th>
        <th class="amount">Side Pots</th>
        <th class="amount">Total Payout</th>
        <th class="paid-cell">Paid</th>
        <th class="signature-cell">Signature</th>
      </tr>
    </thead>
    <tbody>${rows.length > 0 ? renderWinnerRows(rows) : '<tr><td colspan="7" class="empty-table-cell">No payout winners to display.</td></tr>'}</tbody>
  </table>`

const renderVerificationSection = ({
  tournamentName,
  totals,
  winnerCount,
}: {
  tournamentName: string
  totals: PayoutTotals
  winnerCount: number
}): string =>
  `<section class="commissioner" aria-label="Commissioner verification">
    <h2>Commissioner Verification</h2>
    <div class="verification-grid">
      <div><span>Tournament</span><strong>${escapeHtml(tournamentName)}</strong></div>
      <div><span>Total Winners</span><strong>${winnerCount}</strong></div>
      <div><span>Bracket Payouts</span><strong>${formatUsd(totals.bracketPayouts)}</strong></div>
      <div><span>Side Pot Payouts</span><strong>${totals.sidePotPayouts > 0 ? formatUsd(totals.sidePotPayouts) : '&mdash;'}</strong></div>
      <div><span>Verified Total</span><strong>${formatUsd(totals.totalPayout)}</strong></div>
      <div><span>Final Paid Count</span><strong>______ / ${winnerCount}</strong></div>
    </div>
    <div class="commissioner-fields">
      <div class="wide-field"><span>Commissioner / Tournament Director Signature</span><div class="field-line"></div></div>
      <div><span>Printed Name</span><div class="field-line"></div></div>
      <div><span>Date</span><div class="field-line short-line"></div></div>
    </div>
  </section>`

const renderFooter = (): string =>
  `<footer class="footer">
    <strong>BracketWorks &bull; bracketworks.app</strong>
    <span>${DISCLAIMER}</span>
  </footer>`

const renderSheet = ({
  page,
  args,
  totals,
  documentStatus,
}: {
  page: PayoutPage
  args: BuildPayoutPdfHtmlArgs
  totals: PayoutTotals
  documentStatus: string
}): string =>
  `<section class="sheet ${page.continued ? 'continuation-sheet' : ''}">
    <div class="sheet-body">
      ${renderDocumentHeader({
        tournamentName: args.tournamentName,
        squadLabel: args.squadLabel,
        generatedAt: args.generatedAt,
        logoUrl: args.logoUrl,
        programs: args.programs,
        documentStatus,
        continued: page.continued,
      })}
      ${page.continued ? '' : renderSummary({ totals, totalBrackets: args.totalBrackets, totalEntries: args.totalEntries, winnerCount: args.rows.length })}
      ${renderWinnerTable(page.rows)}
      ${page.includeVerification ? renderVerificationSection({ tournamentName: args.tournamentName, totals, winnerCount: args.rows.length }) : ''}
    </div>
    ${renderFooter()}
  </section>`

const renderVerificationSheet = ({
  args,
  totals,
  documentStatus,
}: {
  args: BuildPayoutPdfHtmlArgs
  totals: PayoutTotals
  documentStatus: string
}): string =>
  `<section class="sheet verification-sheet continuation-sheet">
    <div class="sheet-body">
      ${renderDocumentHeader({
        tournamentName: args.tournamentName,
        squadLabel: args.squadLabel,
        generatedAt: args.generatedAt,
        logoUrl: args.logoUrl,
        programs: args.programs,
        documentStatus,
        continued: true,
      })}
      ${renderVerificationSection({ tournamentName: args.tournamentName, totals, winnerCount: args.rows.length })}
    </div>
    ${renderFooter()}
  </section>`

export function buildPayoutPdfHtml(args: BuildPayoutPdfHtmlArgs): string {
  const totals = buildPayoutTotals(args.rows)
  const pages = paginateRows(args.rows)
  const documentStatus = args.documentStatus ?? DEFAULT_DOCUMENT_STATUS
  const needsVerificationSheet = !pages.some(page => page.includeVerification)

  const sheets = [
    ...pages.map(page => renderSheet({ page, args, totals, documentStatus })),
    ...(needsVerificationSheet ? [renderVerificationSheet({ args, totals, documentStatus })] : []),
  ].join('')

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Payout Distribution - ${escapeHtml(args.tournamentName)}</title>
  <link rel="stylesheet" href="/payouts-print.css" />
</head>
<body>
  <main class="payout-document">
    ${sheets}
  </main>
</body>
</html>`
}
