"""add_winner_and_payout_tracking_tables

Revision ID: 06ae6e1faa6c
Revises: 9ebac19384b5
Create Date: 2025-09-27 10:18:33.110878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ae6e1faa6c'
down_revision: Union[str, Sequence[str], None] = '9ebac19384b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.Column('total_prize_pool', sa.Float(), nullable=False),
    sa.Column('total_scratch_pool', sa.Float(), nullable=False),
    sa.Column('total_handicap_pool', sa.Float(), nullable=False),
    sa.Column('total_paid_out', sa.Float(), nullable=False),
    sa.Column('total_unpaid', sa.Float(), nullable=False),
    sa.Column('scratch_brackets_count', sa.Integer(), nullable=False),
    sa.Column('handicap_brackets_count', sa.Integer(), nullable=False),
    sa.Column('total_winners', sa.Integer(), nullable=False),
    sa.Column('scratch_entry_fee', sa.Float(), nullable=False),
    sa.Column('handicap_entry_fee', sa.Float(), nullable=False),
    sa.Column('house_percentage', sa.Float(), nullable=True),
    sa.Column('house_amount', sa.Float(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('finalized_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_summary_id'), 'payout_summary', ['id'], unique=False)
    op.create_index(op.f('ix_payout_summary_is_finalized'), 'payout_summary', ['is_finalized'], unique=False)
    op.create_index(op.f('ix_payout_summary_squad_id'), 'payout_summary', ['squad_id'], unique=False)
    op.create_index(op.f('ix_payout_summary_tournament_id'), 'payout_summary', ['tournament_id'], unique=False)
    op.create_table('tournament_winner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.Column('bracket_id', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=False),
    sa.Column('bracket_type', sa.String(length=20), nullable=False),
    sa.Column('bracket_name', sa.String(length=100), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('placement_text', sa.String(length=10), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('winning_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bowler_id'], ['bowler.id'], ),
    sa.ForeignKeyConstraint(['bracket_id'], ['generated_bracket.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_winner_bowler_id'), 'tournament_winner', ['bowler_id'], unique=False)
    op.create_index(op.f('ix_tournament_winner_bracket_id'), 'tournament_winner', ['bracket_id'], unique=False)
    op.create_index(op.f('ix_tournament_winner_bracket_type'), 'tournament_winner', ['bracket_type'], unique=False)
    op.create_index(op.f('ix_tournament_winner_id'), 'tournament_winner', ['id'], unique=False)
    op.create_index(op.f('ix_tournament_winner_placement'), 'tournament_winner', ['placement'], unique=False)
    op.create_index(op.f('ix_tournament_winner_squad_id'), 'tournament_winner', ['squad_id'], unique=False)
    op.create_index(op.f('ix_tournament_winner_tournament_id'), 'tournament_winner', ['tournament_id'], unique=False)
    op.create_table('tournament_payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.Column('bracket_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=False),
    sa.Column('bracket_type', sa.String(length=20), nullable=False),
    sa.Column('bracket_name', sa.String(length=100), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('prize_pool_total', sa.Float(), nullable=False),
    sa.Column('payout_percentage', sa.Float(), nullable=False),
    sa.Column('payout_amount', sa.Float(), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('bracket_size', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bowler_id'], ['bowler.id'], ),
    sa.ForeignKeyConstraint(['bracket_id'], ['generated_bracket.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['tournament_winner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_payout_bowler_id'), 'tournament_payout', ['bowler_id'], unique=False)
    op.create_index(op.f('ix_tournament_payout_bracket_id'), 'tournament_payout', ['bracket_id'], unique=False)
    op.create_index(op.f('ix_tournament_payout_bracket_type'), 'tournament_payout', ['bracket_type'], unique=False)
    op.create_index(op.f('ix_tournament_payout_id'), 'tournament_payout', ['id'], unique=False)
    op.create_index(op.f('ix_tournament_payout_is_paid'), 'tournament_payout', ['is_paid'], unique=False)
    op.create_index(op.f('ix_tournament_payout_squad_id'), 'tournament_payout', ['squad_id'], unique=False)
    op.create_index(op.f('ix_tournament_payout_tournament_id'), 'tournament_payout', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_tournament_payout_winner_id'), 'tournament_payout', ['winner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_payout_winner_id'), table_name='tournament_payout')
    op.drop_index(op.f('ix_tournament_payout_tournament_id'), table_name='tournament_payout')
    op.drop_index(op.f('ix_tournament_payout_squad_id'), table_name='tournament_payout')
    op.drop_index(op.f('ix_tournament_payout_is_paid'), table_name='tournament_payout')
    op.drop_index(op.f('ix_tournament_payout_id'), table_name='tournament_payout')
    op.drop_index(op.f('ix_tournament_payout_bracket_type'), table_name='tournament_payout')
    op.drop_index(op.f('ix_tournament_payout_bracket_id'), table_name='tournament_payout')
    op.drop_index(op.f('ix_tournament_payout_bowler_id'), table_name='tournament_payout')
    op.drop_table('tournament_payout')
    op.drop_index(op.f('ix_tournament_winner_tournament_id'), table_name='tournament_winner')
    op.drop_index(op.f('ix_tournament_winner_squad_id'), table_name='tournament_winner')
    op.drop_index(op.f('ix_tournament_winner_placement'), table_name='tournament_winner')
    op.drop_index(op.f('ix_tournament_winner_id'), table_name='tournament_winner')
    op.drop_index(op.f('ix_tournament_winner_bracket_type'), table_name='tournament_winner')
    op.drop_index(op.f('ix_tournament_winner_bracket_id'), table_name='tournament_winner')
    op.drop_index(op.f('ix_tournament_winner_bowler_id'), table_name='tournament_winner')
    op.drop_table('tournament_winner')
    op.drop_index(op.f('ix_payout_summary_tournament_id'), table_name='payout_summary')
    op.drop_index(op.f('ix_payout_summary_squad_id'), table_name='payout_summary')
    op.drop_index(op.f('ix_payout_summary_is_finalized'), table_name='payout_summary')
    op.drop_index(op.f('ix_payout_summary_id'), table_name='payout_summary')
    op.drop_table('payout_summary')
    # ### end Alembic commands ###
