"""create_scores_table

Revision ID: 08f4e14df868
Revises: 9ebf3657909f
Create Date: 2025-09-22 20:55:55.964652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f4e14df868'
down_revision: Union[str, Sequence[str], None] = '9ebf3657909f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('game1_scratch', sa.Integer(), nullable=True),
    sa.Column('game1_total', sa.Integer(), nullable=True),
    sa.Column('game2_scratch', sa.Integer(), nullable=True),
    sa.Column('game2_total', sa.Integer(), nullable=True),
    sa.Column('game3_scratch', sa.Integer(), nullable=True),
    sa.Column('game3_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bowler_id'], ['bowler.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_bowler_id'), 'score', ['bowler_id'], unique=False)
    op.create_index(op.f('ix_score_id'), 'score', ['id'], unique=False)
    op.create_index(op.f('ix_score_squad_id'), 'score', ['squad_id'], unique=False)
    op.create_index(op.f('ix_score_tournament_id'), 'score', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_tournament_id'), table_name='score')
    op.drop_index(op.f('ix_score_squad_id'), table_name='score')
    op.drop_index(op.f('ix_score_id'), table_name='score')
    op.drop_index(op.f('ix_score_bowler_id'), table_name='score')
    op.drop_table('score')
    # ### end Alembic commands ###
