"""fix_match_date_column_type

Revision ID: 9ebac19384b5
Revises: performance_indexes
Create Date: 2025-09-27 09:10:33.846884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ebac19384b5'
down_revision: Union[str, Sequence[str], None] = 'performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def safe_drop_index(index_name, table_name, **kwargs):
    """Safely drop an index, ignoring if it doesn't exist."""
    try:
        op.drop_index(op.f(index_name), table_name=table_name, **kwargs)
    except Exception:
        pass  # Index doesn't exist, which is fine

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_drop_index('idx_bowler_name_search', 'bowler')
    safe_drop_index('idx_bowler_tournament_squad', 'bowler')
    op.alter_column('bracket_match', 'match_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    safe_drop_index('idx_bracket_match_active', 'bracket_match', postgresql_where="((status)::text <> 'completed'::text)")
    safe_drop_index('idx_bracket_match_players', 'bracket_match')
    safe_drop_index('ix_bracket_match_index', 'bracket_match')
    safe_drop_index('ix_bracket_match_round', 'bracket_match')
    op.create_index(op.f('ix_bracket_match_id'), 'bracket_match', ['id'], unique=False)
    op.create_index(op.f('ix_bracket_match_round_id'), 'bracket_match', ['round_id'], unique=False)
    op.drop_constraint(op.f('bracket_match_player_a_id_fkey'), 'bracket_match', type_='foreignkey')
    op.drop_constraint(op.f('bracket_match_round_id_fkey'), 'bracket_match', type_='foreignkey')
    op.drop_constraint(op.f('bracket_match_player_b_id_fkey'), 'bracket_match', type_='foreignkey')
    op.create_foreign_key(None, 'bracket_match', 'bowler', ['player_b_id'], ['id'])
    op.create_foreign_key(None, 'bracket_match', 'bracket_round', ['round_id'], ['id'])
    op.create_foreign_key(None, 'bracket_match', 'bowler', ['player_a_id'], ['id'])
    safe_drop_index('ix_bracket_round_bracket', 'bracket_round')
    safe_drop_index('ix_bracket_round_index', 'bracket_round')
    op.create_index(op.f('ix_bracket_round_bracket_id'), 'bracket_round', ['bracket_id'], unique=False)
    op.create_index(op.f('ix_bracket_round_id'), 'bracket_round', ['id'], unique=False)
    op.drop_constraint(op.f('bracket_round_bracket_id_fkey'), 'bracket_round', type_='foreignkey')
    op.create_foreign_key(None, 'bracket_round', 'generated_bracket', ['bracket_id'], ['id'])
    op.alter_column('bracket_summary', 'generation_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    safe_drop_index('ix_bracket_summary_squad', 'bracket_summary')
    safe_drop_index('ix_bracket_summary_tournament', 'bracket_summary')
    op.create_index(op.f('ix_bracket_summary_id'), 'bracket_summary', ['id'], unique=False)
    op.create_index(op.f('ix_bracket_summary_squad_id'), 'bracket_summary', ['squad_id'], unique=False)
    op.create_index(op.f('ix_bracket_summary_tournament_id'), 'bracket_summary', ['tournament_id'], unique=False)
    op.drop_constraint(op.f('bracket_summary_tournament_id_fkey'), 'bracket_summary', type_='foreignkey')
    op.drop_constraint(op.f('bracket_summary_squad_id_fkey'), 'bracket_summary', type_='foreignkey')
    op.create_foreign_key(None, 'bracket_summary', 'squad', ['squad_id'], ['id'])
    op.create_foreign_key(None, 'bracket_summary', 'tournament', ['tournament_id'], ['id'])
    op.alter_column('generated_bracket', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_bracket', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    safe_drop_index('idx_bracket_tournament_type', 'generated_bracket')
    safe_drop_index('ix_generated_bracket_squad', 'generated_bracket')
    op.drop_index(op.f('ix_generated_bracket_tournament'), table_name='generated_bracket')
    op.drop_index(op.f('ix_generated_bracket_type'), table_name='generated_bracket')
    op.create_index(op.f('ix_generated_bracket_bracket_type'), 'generated_bracket', ['bracket_type'], unique=False)
    op.create_index(op.f('ix_generated_bracket_id'), 'generated_bracket', ['id'], unique=False)
    op.create_index(op.f('ix_generated_bracket_squad_id'), 'generated_bracket', ['squad_id'], unique=False)
    op.create_index(op.f('ix_generated_bracket_tournament_id'), 'generated_bracket', ['tournament_id'], unique=False)
    op.drop_constraint(op.f('generated_bracket_tournament_id_fkey'), 'generated_bracket', type_='foreignkey')
    op.drop_constraint(op.f('generated_bracket_squad_id_fkey'), 'generated_bracket', type_='foreignkey')
    op.create_foreign_key(None, 'generated_bracket', 'squad', ['squad_id'], ['id'])
    op.create_foreign_key(None, 'generated_bracket', 'tournament', ['tournament_id'], ['id'])
    op.drop_index(op.f('idx_score_composite'), table_name='score')
    op.drop_index(op.f('idx_tournament_date_range'), table_name='tournament')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tournament_date_range'), 'tournament', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('idx_score_composite'), 'score', ['tournament_id', 'squad_id', 'bowler_id'], unique=False)
    op.drop_constraint(None, 'generated_bracket', type_='foreignkey')
    op.drop_constraint(None, 'generated_bracket', type_='foreignkey')
    op.create_foreign_key(op.f('generated_bracket_squad_id_fkey'), 'generated_bracket', 'squad', ['squad_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('generated_bracket_tournament_id_fkey'), 'generated_bracket', 'tournament', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_generated_bracket_tournament_id'), table_name='generated_bracket')
    op.drop_index(op.f('ix_generated_bracket_squad_id'), table_name='generated_bracket')
    op.drop_index(op.f('ix_generated_bracket_id'), table_name='generated_bracket')
    op.drop_index(op.f('ix_generated_bracket_bracket_type'), table_name='generated_bracket')
    op.create_index(op.f('ix_generated_bracket_type'), 'generated_bracket', ['bracket_type'], unique=False)
    op.create_index(op.f('ix_generated_bracket_tournament'), 'generated_bracket', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_generated_bracket_squad'), 'generated_bracket', ['squad_id'], unique=False)
    op.create_index(op.f('idx_bracket_tournament_type'), 'generated_bracket', ['tournament_id', 'bracket_type'], unique=False)
    op.alter_column('generated_bracket', 'updated_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_bracket', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'bracket_summary', type_='foreignkey')
    op.drop_constraint(None, 'bracket_summary', type_='foreignkey')
    op.create_foreign_key(op.f('bracket_summary_squad_id_fkey'), 'bracket_summary', 'squad', ['squad_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bracket_summary_tournament_id_fkey'), 'bracket_summary', 'tournament', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bracket_summary_tournament_id'), table_name='bracket_summary')
    op.drop_index(op.f('ix_bracket_summary_squad_id'), table_name='bracket_summary')
    op.drop_index(op.f('ix_bracket_summary_id'), table_name='bracket_summary')
    op.create_index(op.f('ix_bracket_summary_tournament'), 'bracket_summary', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_bracket_summary_squad'), 'bracket_summary', ['squad_id'], unique=False)
    op.alter_column('bracket_summary', 'generation_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'bracket_round', type_='foreignkey')
    op.create_foreign_key(op.f('bracket_round_bracket_id_fkey'), 'bracket_round', 'generated_bracket', ['bracket_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bracket_round_id'), table_name='bracket_round')
    op.drop_index(op.f('ix_bracket_round_bracket_id'), table_name='bracket_round')
    op.create_index(op.f('ix_bracket_round_index'), 'bracket_round', ['bracket_id', 'round_index'], unique=False)
    op.create_index(op.f('ix_bracket_round_bracket'), 'bracket_round', ['bracket_id'], unique=False)
    op.drop_constraint(None, 'bracket_match', type_='foreignkey')
    op.drop_constraint(None, 'bracket_match', type_='foreignkey')
    op.drop_constraint(None, 'bracket_match', type_='foreignkey')
    op.create_foreign_key(op.f('bracket_match_player_b_id_fkey'), 'bracket_match', 'bowler', ['player_b_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('bracket_match_round_id_fkey'), 'bracket_match', 'bracket_round', ['round_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bracket_match_player_a_id_fkey'), 'bracket_match', 'bowler', ['player_a_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_bracket_match_round_id'), table_name='bracket_match')
    op.drop_index(op.f('ix_bracket_match_id'), table_name='bracket_match')
    op.create_index(op.f('ix_bracket_match_round'), 'bracket_match', ['round_id'], unique=False)
    op.create_index(op.f('ix_bracket_match_index'), 'bracket_match', ['round_id', 'match_index'], unique=False)
    op.create_index(op.f('idx_bracket_match_players'), 'bracket_match', ['player_a_id', 'player_b_id'], unique=False)
    op.create_index(op.f('idx_bracket_match_active'), 'bracket_match', ['status'], unique=False, postgresql_where="((status)::text <> 'completed'::text)")
    op.alter_column('bracket_match', 'match_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('idx_bowler_tournament_squad'), 'bowler', ['tournament_id', 'squad_id'], unique=False)
    op.create_index(op.f('idx_bowler_name_search'), 'bowler', ['name'], unique=False)
    # ### end Alembic commands ###
